import os
import json
import streamlit as st
import pypdf
import google.generativeai as genai
from dotenv import load_dotenv
from fpdf import FPDF

# Load local environment variables if available
load_dotenv()

# Configure Streamlit Page
st.set_page_config(
    page_title="ATS Resume Score & Improvement Analyzer",
    page_icon="📄",
    layout="wide"
)

# Custom Styling
st.markdown("""
    <style>
    .metric-card {
        background-color: #f0f2f6;
        padding: 20px;
        border-radius: 10px;
        text-align: center;
    }
    .stProgress > div > div > div > div {
        background-color: #1f77b4;
    }
    </style>
""", unsafe_allow_html=True)


class PDFReport(FPDF):
    """Custom PDF generator for ATS Evaluation Reports."""
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(31, 119, 180)
        self.cell(0, 10, "ATS Resume Evaluation Report", ln=True, align="C")
        self.set_font("Helvetica", "I", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, "Generated by ATS Resume Score & Optimizer", ln=True, align="C")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")

    def chapter_title(self, title):
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(40, 40, 40)
        self.set_fill_color(240, 242, 246)
        self.cell(0, 8, f"  {title}", ln=True, fill=True)
        self.ln(3)

    def chapter_body(self, body):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(50, 50, 50)
        self.multi_cell(0, 6, body)
        self.ln(5)


def generate_pdf_bytes(result):
    """Generates a downloadable PDF binary from analysis results."""
    pdf = PDFReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # 1. ATS Match Score
    score = result.get("ats_score", 0)
    summary = result.get("summary", "N/A")
    pdf.chapter_title(f"ATS Match Score: {score}%")
    pdf.chapter_body(f"Summary: {summary}")

    # 2. Matching Keywords
    pdf.chapter_title("Matching Keywords")
    matching_kw = ", ".join(result.get("matching_keywords", [])) or "None identified"
    pdf.chapter_body(matching_kw)

    # 3. Missing Keywords
    pdf.chapter_title("Missing Keywords")
    missing_kw = ", ".join(result.get("missing_keywords", [])) or "None identified"
    pdf.chapter_body(missing_kw)

    # 4. Bullet Point Improvements
    pdf.chapter_title("Bullet Point Recommendations")
    improvements = result.get("bullet_improvements", [])
    if improvements:
        bullet_text = ""
        for idx, item in enumerate(improvements, 1):
            bullet_text += f"{idx}. Original: {item.get('original_phrase', 'N/A')}\n"
            bullet_text += f"   Improved: {item.get('improved_phrase', 'N/A')}\n\n"
        pdf.chapter_body(bullet_text.strip())
    else:
        pdf.chapter_body("No specific bullet point revisions suggested.")

    # 5. Formatting Suggestions
    pdf.chapter_title("Formatting & Structure Suggestions")
    fmt_feedback = "\n".join([f"- {item}" for item in result.get("formatting_and_layout_feedback", [])]) or "None"
    pdf.chapter_body(fmt_feedback)

    # 6. Actionable Next Steps
    pdf.chapter_title("Priority Action Steps")
    next_steps = "\n".join([f"{idx}. {step}" for idx, step in enumerate(result.get("actionable_next_steps", []), 1)]) or "None"
    pdf.chapter_body(next_steps)

    return bytes(pdf.output())


def extract_text_from_pdf(uploaded_file):
    """Extract text from uploaded PDF file using pypdf."""
    try:
        reader = pypdf.PdfReader(uploaded_file)
        extracted_text = ""
        for page in reader.pages:
            text = page.extract_text()
            if text:
                extracted_text += text + "\n"
        return extracted_text.strip()
    except Exception as e:
        st.error(f"Error reading PDF file: {e}")
        return None


def analyze_resume(resume_text, job_description, api_key):
    """Call Google Gemini 1.5 Flash to analyze resume against ATS standards."""
    genai.configure(api_key=api_key)
    model = genai.GenerativeModel("gemini-1.5-flash")

    prompt = f"""
You are an expert HR Specialist and Advanced Applicant Tracking System (ATS) evaluator.
Analyze the provided candidate's resume against the target Job Description.

Resume Text:
\"\"\"
{resume_text}
\"\"\"

Job Description:
\"\"\"
{job_description}
\"\"\"

Provide your analysis ONLY in valid JSON format with the following exact keys:
{{
  "ats_score": <number between 0 and 100>,
  "summary": "<2-3 sentence overview of how well the resume matches>",
  "matching_keywords": ["list", "of", "matching", "key", "skills"],
  "missing_keywords": ["list", "of", "critical", "missing", "keywords"],
  "bullet_improvements": [
    {{
      "original_phrase": "<weak or vague phrase from resume>",
      "improved_phrase": "<action-oriented, quantified replacement>"
    }}
  ],
  "formatting_and_layout_feedback": ["list", "of", "layout/structure", "suggestions"],
  "actionable_next_steps": ["step 1", "step 2", "step 3"]
}}

Do not wrap the JSON inside markdown code blocks like ```json ... ```. Output raw valid JSON only.
"""

    response = model.generate_content(prompt)
    raw_response = response.text.strip()

    if raw_response.startswith("```json"):
        raw_response = raw_response[7:]
    if raw_response.startswith("```"):
        raw_response = raw_response[3:]
    if raw_response.endswith("```"):
        raw_response = raw_response[:-3]

    return json.loads(raw_response.strip())


# App Interface
st.title("📄 ATS Resume Score & Optimizer")
st.caption("Powered by Streamlit & Google Gemini 1.5 Flash")

# Sidebar - API Key Management
with st.sidebar:
    st.header("🔑 Configuration")
    api_key_input = st.text_input(
        "Google Gemini API Key",
        type="password",
        help="Enter your API key from Google AI Studio. If deployed on Streamlit Cloud, add GOOGLE_API_KEY to Secrets."
    )
    api_key = api_key_input or st.secrets.get("GOOGLE_API_KEY", None) or os.getenv("GOOGLE_API_KEY")

    st.divider()
    st.markdown("### How to use:")
    st.markdown("1. Enter your **Gemini API Key**.\n2. Paste the **Job Description**.\n3. Upload your **PDF Resume**.\n4. Click **Analyze Resume**.")

# Main Layout
col_input1, col_input2 = st.columns(2)

with col_input1:
    job_description = st.text_area("📋 Paste Job Description", height=250, placeholder="Paste job requirements, skills, and duties here...")

with col_input2:
    uploaded_file = st.file_uploader("📤 Upload Resume (PDF only)", type=["pdf"])

st.divider()

if st.button("🚀 Analyze Resume", type="primary", use_container_width=True):
    if not api_key:
        st.error("Please provide a Google Gemini API key in the sidebar or application secrets.")
    elif not job_description.strip():
        st.warning("Please paste a Job Description to compare your resume against.")
    elif uploaded_file is None:
        st.warning("Please upload a PDF Resume.")
    else:
        with st.spinner("Extracting text and analyzing with Gemini 1.5 Flash..."):
            resume_text = extract_text_from_pdf(uploaded_file)

            if not resume_text:
                st.error("Could not extract text from the uploaded PDF. Ensure it's not a scanned image-only PDF.")
            else:
                try:
                    result = analyze_resume(resume_text, job_description, api_key)
                    st.session_state["analysis_result"] = result
                except Exception as e:
                    st.error(f"Analysis failed: {str(e)}")

# Display Analysis Results from Session State
if "analysis_result" in st.session_state:
    result = st.session_state["analysis_result"]

    # Header & Download Button Row
    res_col1, res_col2 = st.columns([3, 1])
    with res_col1:
        st.subheader("📊 ATS Match Score")
    with res_col2:
        pdf_bytes = generate_pdf_bytes(result)
        st.download_button(
            label="📥 Download PDF Report",
            data=pdf_bytes,
            file_name="ATS_Resume_Evaluation_Report.pdf",
            mime="application/pdf",
            use_container_width=True
        )

    score = result.get("ats_score", 0)
    score_col1, score_col2 = st.columns([1, 3])
    with score_col1:
        st.metric(label="Match Rate", value=f"{score}%")
    with score_col2:
        st.progress(score / 100)
        st.write(result.get("summary", ""))

    st.divider()

    # Keywords Analysis
    col_kw1, col_kw2 = st.columns(2)
    with col_kw1:
        st.markdown("### ✅ Matching Keywords")
        for kw in result.get("matching_keywords", []):
            st.success(kw)

    with col_kw2:
        st.markdown("### ❌ Missing Keywords")
        for kw in result.get("missing_keywords", []):
            st.error(kw)

    st.divider()

    # Bullet Point Rewrites
    st.markdown("### ✏️ Bullet Point Improvements")
    improvements = result.get("bullet_improvements", [])
    if improvements:
        for item in improvements:
            with st.expander(f"Original: {item.get('original_phrase', 'Vague bullet point')}"):
                st.markdown(f"**Recommended Revision:**\n> {item.get('improved_phrase', '')}")
    else:
        st.info("No specific bullet point revisions suggested.")

    st.divider()

    # Formatting & Next Steps
    col_fmt, col_steps = st.columns(2)
    with col_fmt:
        st.markdown("### 📐 Formatting & Structure Suggestions")
        for tip in result.get("formatting_and_layout_feedback", []):
            st.markdown(f"- {tip}")

    with col_steps:
        st.markdown("### 🎯 Priority Action Steps")
        for idx, step in enumerate(result.get("actionable_next_steps", []), 1):
            st.markdown(f"**{idx}.** {step}")